# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-21 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_auto_20160412_1123'),
        ('cleansing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleansingInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_task_identifier', models.CharField(max_length=100)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.Organization')),
            ],
        ),
    ]
