# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-30 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingImportRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_pk', models.CharField(blank=True, max_length=40, null=True)),
                ('was_in_database', models.BooleanField(default=False)),
                ('is_missing_from_import', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DataCoercionMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_string', models.TextField()),
                ('source_type', models.CharField(max_length=50)),
                ('destination_value', models.CharField(blank=True, max_length=255, null=True)),
                ('destination_type', models.CharField(blank=True, max_length=255, null=True)),
                ('is_mapped', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=0)),
                ('was_a_human_decision', models.BooleanField(default=False)),
                ('valid_destination_value', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('deleted', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, max_length=500, null=True, upload_to=b'data_imports')),
                ('uploaded_filename', models.CharField(blank=True, max_length=255)),
                ('file_size_in_bytes', models.IntegerField(blank=True, null=True)),
                ('export_file', models.FileField(blank=True, null=True, upload_to=b'data_imports/exports')),
                ('cached_first_row', models.TextField(blank=True, null=True)),
                ('cached_mapped_columns', models.TextField(blank=True, null=True)),
                ('cached_second_to_fifth_row', models.TextField(blank=True, null=True)),
                ('has_header_row', models.BooleanField(default=True)),
                ('mapping_completion', models.IntegerField(blank=True, null=True)),
                ('mapping_done', models.BooleanField(default=False)),
                ('mapping_error_messages', models.TextField(blank=True, null=True)),
                ('matching_completion', models.IntegerField(blank=True, null=True)),
                ('matching_done', models.BooleanField(default=False)),
                ('num_coercion_errors', models.IntegerField(blank=True, default=0, null=True)),
                ('num_coercions_total', models.IntegerField(blank=True, default=0, null=True)),
                ('num_columns', models.IntegerField(blank=True, null=True)),
                ('num_mapping_errors', models.IntegerField(default=0)),
                ('num_mapping_warnings', models.IntegerField(default=0)),
                ('num_rows', models.IntegerField(blank=True, null=True)),
                ('num_tasks_complete', models.IntegerField(blank=True, null=True)),
                ('num_tasks_total', models.IntegerField(blank=True, null=True)),
                ('num_validation_errors', models.IntegerField(blank=True, null=True)),
                ('raw_save_done', models.BooleanField(default=False)),
                ('raw_save_completion', models.IntegerField(blank=True, null=True)),
                ('source_type', models.CharField(blank=True, max_length=63, null=True)),
                ('source_program', models.CharField(blank=True, max_length=80)),
                ('source_program_version', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, default=b'Unnamed Dataset', max_length=255, null=True, verbose_name=b'Name Your Dataset')),
                ('app', models.CharField(default=b'seed', help_text=b'The application (e.g. BPD or SEED) for this dataset', max_length=64, verbose_name=b'Destination App')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('merge_analysis_done', models.BooleanField(default=False)),
                ('merge_analysis_active', models.BooleanField(default=False)),
                ('merge_analysis_queued', models.BooleanField(default=False)),
                ('premerge_analysis_done', models.BooleanField(default=False)),
                ('premerge_analysis_active', models.BooleanField(default=False)),
                ('premerge_analysis_queued', models.BooleanField(default=False)),
                ('matching_active', models.BooleanField(default=False)),
                ('matching_done', models.BooleanField(default=False)),
                ('is_imported_live', models.BooleanField(default=False)),
                ('keep_missing_buildings', models.BooleanField(default=True)),
                ('status', models.IntegerField(choices=[(0, b'Uploading'), (1, b'Machine Mapping'), (2, b'Needs Mapping'), (3, b'Machine Cleaning'), (4, b'Needs Cleaning'), (5, b'Ready to Merge'), (6, b'Merging'), (7, b'Merge Complete'), (8, b'Importing'), (9, b'Live'), (10, b'Unknown'), (11, b'Matching')], default=0)),
                ('import_completed_at', models.DateTimeField(blank=True, null=True)),
                ('merge_completed_at', models.DateTimeField(blank=True, null=True)),
                ('mcm_version', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='TableColumnMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(default=b'', max_length=64)),
                ('source_string', models.TextField()),
                ('destination_model', models.CharField(blank=True, max_length=255, null=True)),
                ('destination_field', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0)),
                ('ignored', models.BooleanField(default=False)),
                ('was_a_human_decision', models.BooleanField(default=False)),
                ('error_message_text', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('import_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_importer.ImportFile')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='ValidationOutlier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValidationRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passes', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RangeValidationRule',
            fields=[
                ('validationrule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data_importer.ValidationRule')),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('limit_min', models.BooleanField(default=False)),
                ('limit_max', models.BooleanField(default=False)),
            ],
            bases=('data_importer.validationrule',),
        ),
        migrations.AddField(
            model_name='validationrule',
            name='table_column_mapping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_importer.TableColumnMapping'),
        ),
        migrations.AddField(
            model_name='validationoutlier',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_importer.ValidationRule'),
        ),
    ]
